---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "bioinfotongli_omezarrparse"
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
      - fire==0.5.0
      - ome-zarr==0.8.0
      - ome-types==0.5.1