---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "tiledimagesegmentation_cellposewrapper"
description: cellpose is an anatomical segmentation algorithm written in Python 3 by Carsen Stringer and Marius Pachitariu.
keywords:
  - cellpose
  - segmentation
  - deeplearning
  - imaging
  - image analysis
tools:
  - "tiledimagesegmentation":
      description: "A toolset for tiled image segmentation"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: [MIT]
      identifier: 


input:
  - - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test' ]`

    - x_min:
        type: integer
        description: x_min of the region of interest

    - x_max:
        type: integer
        description: x_max of the region of interest

    - y_min:
        type: integer
        description: y_min of the region of interest

    - y_max:
        type: integer
        description: y_max of the region of interest
    
    - imgs:
        type: file
        description: raw images for segmentation
        pattern: "*.{tif,ome.tif,ome.tiff}"

    - cell_diameter:
        type: integer
        description: expected cell diameter in pixels
  
output:
  - - meta:
      type: map
      description:
        Groovy Map containing sample information
        e.g. `[ id:'test' ]`

    - "${stem}/${stem}_cp_outlines.txt":
      type: file
      description:  outlines of the segmented cells
      pattern: "*.txt"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  

authors:
  - "@BioinfoTongLI"
