# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "parallelspatialdataquery"
description: "This subworkflow is used to query spatial data in parallel in multiple processes"
keywords:
  - spatial genomics
  - spatial transcriptomics
  - spatial data format

input:
  - spatialdata:
      type: file
      description: |
        Structure: [ val(meta), path(spatialdata) ]
      pattern: "*.{zarr/sdata}"

output:
  - spatialdata_subset:
      type: file
      description: |
        Structure: [ val(meta), path(spatialdata_subset) ]
      pattern: "*.{sdata/zarr}"

  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@BioinfoTongLI"
maintainers:
  - "@BioinfoTongLI"
