---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "fractal_thresholding"
description: write your description here
keywords:
  - thresholding
  - image analysis
  - segmentation
tools:
  - "fractal":
      description: "Fractal is a framework developed at the BioVisionCenter to process bioimaging data at scale in the OME-Zarr format and prepare the images for interactive visualization."
      homepage: "https://fractal-analytics-platform.github.io/"
      documentation: "https://fractal-analytics-platform.github.io/"
      tool_dev_url: ""
      doi: ""
      licence: 
      identifier: 

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
  
    - ome_zarr:
        type: file
        description: OME-Zarr file/folder
        pattern: "*.zarr"
        # ontologies:# doesn't seem to have an ID for ome-zarr ?
        #   - edam: "http://edamontology.org/format_25722"
    - threshold:
        type: int
        description: Threshold value for segmentation
        
    - label_name:
        type: string
        description: Name of the label for the segmented image
        default: "segmentation"

    - channel_name:
        type: string
        description: Name of the channel to be segmented
        default: "DAPI"
          

output:
  - bam:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`

    - "*":
        type: file
        description: zarr folder containing the segmented images
        # pattern: "*.{bam,cram,sam}"
        # ontologies:
        #   - edam: "http://edamontology.org/format_25722"
        #   - edam: "http://edamontology.org/format_2573"
        #   - edam: "http://edamontology.org/format_3462"
          
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@BioinfoTongLI"
maintainers:
  - "@BioinfoTongLI"
