---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "tiledimagesegmentation_stardistwrapper"
description: "A wrapper of Stardist: star-convex object detection for 2D and 3D images"
keywords:
  - segmentation
  - imaging
  - image_analysis
  - deep-learning
tools:
  - "tiledimagesegmentation":
      description: "Python implementation of star-convex object detection for 2D and 3D images"
      homepage: "https://github.com/stardist/stardist/tree/main"
      tool_dev_url: "https://github.com/stardist/stardist/tree/main"
      doi: ""
      licence: ["BSD-3-Clause"]
      documentation: ""
      identifier: 

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1']`
  
    - imgs:
        type: file
        description: raw images for segmentation
        pattern: "*.{tif,ome.tif,ome.tiff}"
        ontologies:
          - edam: "http://edamontology.org/format_25722"
          
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', channels:[0,1] ]`

  - segmentation:
      type: file
      description: folder contains segmentation information
      pattern: "*"
      ontologies:
        - edam: "http://edamontology.org/format_25722"
          
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@BioinfoTongLI"
maintainers:
  - "@BioinfoTongLI"
