---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "tiledimagesegmentation_generatetilecoords"
description: a helper script to generate tiles from an 2D image file
keywords:
  - image
  - tiling
  - slicing
tools:
  - "tiledimagesegmentation":
      description: "A toolset for tiled image segmentation"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: [MIT]
      identifier: 

input:
  - - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test' ]`

    - image:
        type: file
        description: Tifffile compatible file formats
        pattern: "*.{tif,ome.tif,ome.tiff}"

output:
  - - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test' ]`

    - "{output_name}":
        type: file
        description: a csv file contains the information of tiles
        pattern: "*.csv"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@BioinfoTongLI"
maintainers:
  - "@BioinfoTongLI"
